apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer-api
  annotations:
    fluxcd.io/automated: "true"  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dealer-api
  template:
    metadata:
      labels:
        app: dealer-api
    spec:
      containers:
      - name: dealer-api
        image: 289952279049.dkr.ecr.ap-northeast-1.amazonaws.com/ds-test
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
      nodeSelector:
        eks.amazonaws.com/nodegroup: api-ng
