apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer-api
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dealer-api
  template:
    metadata:
      labels:
        app: dealer-api
    spec:
      terminationGracePeriodSeconds: 30
      readinessGates:
      - conditionType: target-health.alb.ingress.k8s.aws/chekt-dealer-api_chekt-dealer-api_3000
      containers:
      - name: dealer-api
        image: 289952279049.dkr.ecr.ap-northeast-1.amazonaws.com/ds-test
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          failureThreshold: 2
          periodSeconds: 10
          timeoutSeconds: 5
      nodeSelector:
        eks.amazonaws.com/nodegroup: api-ng
